= Collection of Sources from Design Pattern Course

:sectnums:
:toc:
:toclevels: 4
:toc-title:
:keywords: C++, Design Patterns

== Introduction

References from:

* Design Patterns Elements of Resusable Object-Oriented Software (Gang-of-Four)

.Possible Structure for examples
|===

3+^| SOLID Design Principles

^| Creational ^| Structural ^| Behavioral

|===

=== Creational

* Builder
* Factories
** Abstract Factory
** Factory Method
* Prototype
* Singleton

=== Structural
* Adapter
* Bridge
* Composite
* Decorator
* Facade
* Flyweight
* Proxy

=== Behavioral
* Chain of Responsibility
* Command
* Interpreter
* Iterator
* Mediator
* Memento
* Observer
* State
* Strategy
* Template Method
* Visitor

== SOLID Design Principle

Design principles introduced by Robert C. Martin

References:

* Agile Software Development Principles, Patterns, and Practices by Robert C. Martin
* Agile Principles, Patterns, and Practices in C# by Robert C. Martin, and Micah Martin


=== **(S)**ingle Responsibility Principle

Examples available link:02.SOLID.Design.Principle/01.SingleResponsibilityPrinciple/README.adoc[here].

=== **(O)**pen Closed Principle

Examples available link:02.SOLID.Design.Principle/02.Open-ClosedPrinciple/README.adoc[here].

=== **(L)**iskov Substitution Principle

Examples available link:02.SOLID.Design.Principle/03.LiskovSubstitutionPrinciple/README.adoc[here].

=== **(I)**nterface Segregation Principle

Examples available link:02.SOLID.Design.Principle/04.InterfaceSegregationPrinciple/README.adoc[here].

=== **(D)**ependency Inversion Principle

Examples available link:02.SOLID.Design.Principle/05.DependencyInversionPrinciple/README.adoc[here].


== Builder

* Some objects are simple and can be created in a single constructor call
* Other Objects require a lot of ceremony to create
* Having an object with 10 constructor arguments is not productive
* Instead, opt for piecewise construction
* Builder provides an API for constructing an object step-by-step

=== Creational Builder Intro

Example available link:03.Builder/01.BuilderIntro/README.adoc[here].
