/* 
	common subexpression elimination
	Access of elements in arrays causes implicit common 
	subexpressions

	The unoptimized IC generated by the Code generator looks
	as follows

	(1) _t0 := index * 12
	(2) _t1 := &all_students
	(3) _t0 := _t0 + 0
	(4) _t1[_t0] := age
	(5) _t2 := index * 12
	(6) _t3 := &all_students
	(7) _t2 := _t2 + 4
	(8) _t3[_t2] := roll_no
	(9) _t4 := index * 12
	(10) _t5 := &all_students
	(11) _t4 := _t4 + 8
	(12) _t5[_t4] := grade

	We can see that the the expression , index * 12 is computed
	each time an element is accessed. Also, the computation
	of &all_students forms another common subexpression that
	can be eliminated. The regeneration of IC from DAG eliminates
	these subexpressions. The optimized code is as follows

	(1) _t6 := index * 12
	(2) _t1 := &all_students
	(3) _t0 := _t6 + 0
	(4) _t1[_t0] := age
	(5) _t2 := _t6 + 4
	(6) _t1[_t2] := roll_no
	(7) _t4 := _t6 + 8
	(8) _t1[_t4] := grade

*/

struct student
{
	int age;
	int roll_no;
	int grade;
}all_students[10];

void set_elements(int index,char *name,int age,int roll_no,int grade);


void
set_elements(int index,char *name,int age,int roll_no,int grade)
{
	all_students[index].age=age;
	all_students[index].roll_no=roll_no;
	all_students[index].grade=grade;
}
	

